#!/usr/bin/env bash
# setup-tunnel.sh — Configure Cloudflare Tunnel (cloudflared) to expose the
# local server to the public internet at a stable hostname.
#
# Prerequisites:
#   - A domain managed by Cloudflare (free tier is fine)
#   - 'cloudflared' installed on this machine (brew install cloudflared /
#     apt install cloudflared / download from https://pkg.cloudflare.com/)
#   - Run: cloudflared tunnel login        (interactive, opens a browser)
#
# Usage:
#   ./deploy/setup-tunnel.sh --hostname mem.example.com
#                           --tunnel-name claude-mem
#
# After this script finishes:
#   - The tunnel runs as a systemd / launchd / foreground process
#   - Public DNS points at Cloudflare's edge → your laptop:37877
#   - Run client-config.sh --url https://mem.example.com to register a device
#
set -euo pipefail

HOSTNAME=""
TUNNEL_NAME="claude-mem"
SERVICE=1
while [[ $# -gt 0 ]]; do
  case "$1" in
    --hostname) HOSTNAME="$2"; shift 2 ;;
    --tunnel-name) TUNNEL_NAME="$2"; shift 2 ;;
    --no-service) SERVICE=0; shift ;;
    -h|--help)
      sed -n '2,18p' "$0"; exit 0 ;;
    *) echo "Unknown flag: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$HOSTNAME" ]]; then
  echo "ERROR: --hostname is required (e.g. mem.example.com)" >&2
  exit 1
fi
if ! command -v cloudflared >/dev/null 2>&1; then
  echo "ERROR: cloudflared not found on PATH." >&2
  echo "Install: https://pkg.cloudflare.com/ or 'brew install cloudflared'" >&2
  exit 1
fi
if ! curl -fsS http://127.0.0.1:37877/healthz >/dev/null 2>&1; then
  echo "ERROR: server is not reachable on 127.0.0.1:37877 — start the stack first." >&2
  exit 1
fi

CREDS_DIR="$HOME/.cloudflared"
mkdir -p "$CREDS_DIR"

# ─── 1. Login (idempotent — only prompts if needed) ───────────────────────────
if [[ ! -f "$CREDS_DIR/cert.pem" ]]; then
  echo "[1/4] logging in to Cloudflare (browser will open)…"
  cloudflared tunnel login
fi

# ─── 2. Create the tunnel (idempotent) ────────────────────────────────────────
if ! cloudflared tunnel info "$TUNNEL_NAME" >/dev/null 2>&1; then
  echo "[2/4] creating tunnel '$TUNNEL_NAME'"
  cloudflared tunnel create "$TUNNEL_NAME"
else
  echo "[2/4] tunnel '$TUNNEL_NAME' already exists"
fi

# ─── 3. Config file ───────────────────────────────────────────────────────────
CONFIG="$CREDS_DIR/config.yml"
TUNNEL_ID="$(cloudflared tunnel info "$TUNNEL_NAME" | awk -F': *' '/^Tunnel ID/ {print $2; exit}')"

if [[ -z "$TUNNEL_ID" ]]; then
  echo "ERROR: could not determine tunnel ID for $TUNNEL_NAME" >&2
  exit 1
fi

cat > "$CONFIG" <<EOF
# Generated by claude-mem deploy/setup-tunnel.sh on $(date -Iseconds 2>/dev/null || date)
tunnel: $TUNNEL_ID
credentials-file: $CREDS_DIR/${TUNNEL_ID}.json

ingress:
  - hostname: $HOSTNAME
    service: http://127.0.0.1:37877
  - service: http_status:404
EOF
echo "[3/4] wrote $CONFIG"

# ─── 4. DNS route (idempotent) + run ──────────────────────────────────────────
echo "[4/4] routing DNS $HOSTNAME → $TUNNEL_NAME"
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" || true

if [[ "$SERVICE" == "1" ]]; then
  echo
  echo "Installing cloudflared as a system service…"
  cloudflared service install 2>/dev/null || true
  case "$(uname -s)" in
    Linux)  sudo systemctl enable --now cloudflared ;;
    Darwin) sudo brew services start cloudflared ;;
    *)      echo "Start the tunnel manually: cloudflared tunnel run $TUNNEL_NAME" ;;
  esac
else
  echo
  echo "Run the tunnel manually:"
  echo "  cloudflared tunnel run $TUNNEL_NAME"
fi

cat <<EOF

════════════════════════════════════════════════════════════════════════
  Tunnel ready
════════════════════════════════════════════════════════════════════════
  Public URL: https://$HOSTNAME
  Local URL:  http://127.0.0.1:37877

  Verify with: curl -fsS https://$HOSTNAME/healthz

  Register a remote device:
    ./deploy/client-config.sh --url https://$HOSTNAME --print

════════════════════════════════════════════════════════════════════════
EOF